require "../MyCode/common"
require "../MyCode/QuestLine"
require "../MyCode/jianding"
require "../MyCode/location"
require "../MyCode/way"
require "../MyCode/battle"
require "../MyCode/name"
require "../MyCode/learnSkill"
require "../MyCode/lingwu"
require "../MyCode/dazuo"
require "../MyCode/quest"
require "../MyCode/DefineValue"
require "../MyCode/remote"
require "../MyCode/fullme"
require "../MyCode/nanjue"
require "../MyCode/hubiao"
require "../MyCode/hubiaoOther"

Note("!!!º”‘ÿÕÍ≥…!!!");