-------------------------------------
--             任务链              --
-------------------------------------
QuestOver = QuestOver or {};
QuestOver.tQuest = {"tz", "hyd", "mrpr", "gsz", "hsz", "mzj", "yujie", "wat", "xf"};


-------------------------------------
--              地点               --
-------------------------------------
Name = Name or {};

Name.LocateRepeat = {"嘉兴嘉兴", "桃源桃源", "福州福州", "牙山牙山", "岳阳岳阳", "黄河南岸黄河南岸", "提督府提督府", "华山华山", "天龙寺天龙寺", "黄河北岸黄河北岸", "杀手帮杀手帮", "平西王府平西王府", "大理大理", 
	"丝绸之路丝绸之路", "星宿星宿", "苏州苏州", "南昌南昌", "洛阳洛阳", "灵州灵州", "西湖西湖", "晋阳晋阳", "扬州扬州", "襄阳襄阳", "临安府临安府", "凌霄凌霄", "明教明教", "兰州很兰州"};

Name.Locate = {};
Name.Locate["康亲王府康亲王书房"] = "康亲王府书房";
Name.Locate["洛阳大厅"] = "天地会";
Name.Locate["华山书房"] = "华山";
Name.Locate["苏州宝带桥"] = "苏州";
Name.Locate["长江岸边"] = "长江南岸边";
Name.Locate["长江渡口"] = "长江南渡口";
Name.Locate["岳王墓岳  飞  墓"] = "岳飞墓";
Name.Locate["桃源县境"] = "桃源";
Name.Locate["康亲王府王府大门"] = "康亲王府";
Name.Locate["福州城中心"] = "福州";
Name.Locate["泉州很城中心"] = "泉州很";
Name.Locate["信II南阳小广场"] = "信II南阳";
Name.Locate["明教山门"] = "明教";
Name.Locate["提督府正门"] = "提督府";
Name.Locate["星宿巨岩"] = "星宿";
Name.Locate["张家口广场"] = "张家口";
Name.Locate["镇江广场"] = "镇江";
Name.Locate["牙山湾中心"] = "牙山";
Name.Locate["临安府大理寺"] = "杭州";
Name.Locate["成都总督府门前"] = "成都";
Name.Locate["湟中湟中中心"] = "湟中中心";
Name.Locate["江州中央广场"] = "江州";
Name.Locate["小山村打谷场"] = "小村";
Name.Locate["麒麟村小广场"] = "麒麟村";
Name.Locate["明教绿柳山庄大门"] = "绿柳";
Name.Locate["南昌岳麓书院"] = "朱湖UU溪II";
Name.Locate["襄阳帅府大厅"] = "过UU欧境II南格";
Name.Locate["襄阳蒙古金帐"] = "蒙恩南格格恩";
Name.Locate["襄阳后院"] = "襄阳后欧UU院";
Name.Locate["襄阳打铁铺(售盔甲)"] = "襄阳打铁铺";
Name.Locate["襄阳打铁铺(售刀剑)"] = "襄阳打铁铺22";
Name.Locate["荆州荆州"] = "襄阳荆州";
Name.Locate["华山悬崖"] = "华山悬崖阿";
Name.Locate["灵州卫士宿处"] = "灵州卫士树处";
Name.Locate["灵州琴房"] = "灵州琴II南房";
Name.Locate["西湖走廊"] = "西湖走廊暗南格";
Name.Locate["武当武当广场"] = "武当";
Name.Locate["武当香积厨"] = "武当香积厨湖UU";
--Name.Locate["武当复真观11"] = "武当复真观";
Name.Locate["武当武当山门"] = "武当山门";
Name.Locate["武当小路"] = "武当小路UU";
Name.Locate["武当升仙坊"] = "武当升很饿南仙坊";
Name.Locate["大理茶花园"] = "大理茶花园UU";
Name.Locate["大理睡房"] = "大理睡胡UUII房";
Name.Locate["大理库房"] = "大理库UU房";
Name.Locate["大理古道"] = "大理古UU道";
Name.Locate["大理南诏德化碑"] = "大理南少德化碑";
Name.Locate["扬州酒店"] = "扬州酒IIUU店";
Name.Locate["扬州土地庙"] = "丐帮";
Name.Locate["扬州正气山庄的大门"] = "扬州正气山庄大门";
Name.Locate["紫禁城昭德门"] = "紫禁城昭很奥欧德门";
Name.Locate["紫禁城体和殿"] = "紫禁城体II和殿";
Name.Locate["紫禁城南书房"] = "紫禁城南安南书房";
Name.Locate["紫禁城养性殿"] = "紫禁城养性II南格殿";
Name.Locate["紫禁城传心殿"] = "紫禁城穿心殿";
Name.Locate["紫禁城左翼门"] = "紫禁城左翼II门";
Name.Locate["紫禁城熙和门"] = "紫禁城熙和饿门";
Name.Locate["紫禁城西华门"] = "紫禁城西华UU阿门";
Name.Locate["凌霄雪屋"] = "凌霄雪UU饿屋";
Name.Locate["凌霄侧廊"] = "凌霄侧廊阿南格";
Name.Locate["凌霄鞋店"] = "凌霄鞋店II阿南";
Name.Locate["凌霄花厅"] = "凌霄花UU阿厅";
Name.Locate["日月小村庄"] = "日月";
Name.Locate["日月厨房"] = "日月厨UU房";
Name.Locate["泰山南天门"] = "泰山";
Name.Locate["泰山猪圈"] = "泰山猪卷";
Name.Locate["泰山宝藏岭"] = "泰山宝丈岭";
Name.Locate["嘉兴城"] = "嘉兴";
Name.Locate["嘉兴树林"] = "嘉兴树林II南";
Name.Locate["晋阳朝曦门内街"] = "晋阳";
Name.Locate["晋阳南市"] = "晋阳南安南市";
Name.Locate["晋阳麻市"] = "晋阳麻安市";
Name.Locate["中原中原马车总行"] = "中原马车行";
Name.Locate["中原汝州城"] = "中原汝州";
Name.Locate["中原许昌城"] = "中原许昌";
Name.Locate["桃花岛大厅"] = "桃花岛";
Name.Locate["桃花岛海滩"] = "桃花岛海滩暗南";
Name.Locate["桃花岛走廊"] = "桃花岛走廊暗南格";
Name.Locate["曲阜孔庙"] = "曲阜";
Name.Locate["曲阜石门寺"] = "曲阜石门寺II";
Name.Locate["古墓断龙石"] = "古墓";
Name.Locate["古墓溪底"] = "古墓溪底II";
Name.Locate["古墓古墓派休息室"] = "古墓派休息室";
Name.Locate["古墓古墓墓洞"] = "古墓墓洞欧南格";
Name.Locate["古墓墓洞"] = "古墓墓洞欧南格";
Name.Locate["临安府大厅"] = "韩世忠";
Name.Locate["临安府临安府"] = "临安府";
Name.Locate["白驼大门"] = "白驼";
Name.Locate["白驼蛇谷坡地"] = "白驼蛇谷坡欧地II";
Name.Locate["白驼农舍"] = "白驼农欧南格舍";
Name.Locate["白驼树林"] = "白驼树林II南";
Name.Locate["白驼厨房"] = "白驼厨湖UU房";
Name.Locate["白驼山沟"] = "白驼山沟欧UU";
Name.Locate["建康"] = "建康中央广场";
Name.Locate["建康中城"] = "建康";
Name.Locate["建康清凉寺"] = "建康清凉寺II";
Name.Locate["建康石城门"] = "建康石很II城门";
Name.Locate["峨嵋千佛庵大殿"] = "峨嵋";
Name.Locate["峨眉后山峨嵋金顶"] = "峨眉后山金顶";
Name.Locate["峨眉后山后山"] = "峨眉后山";
Name.Locate["峨嵋后山山洞"] = "峨嵋后山山洞欧";
Name.Locate["峨眉后山山洞"] = "峨嵋后山山洞欧";
Name.Locate["峨嵋石坊"] = "峨嵋石后II坊";
Name.Locate["峨嵋花园"] = "峨嵋花UU阿园";
Name.Locate["少林方丈楼"] = "少林";
Name.Locate["少林少林寺"] = "22虚UU";
Name.Locate["少林竹林"] = "少林竹林II南";
Name.Locate["少林走廊"] = "少林走廊安";
Name.Locate["少林禅院"] = "少林蚕院";
Name.Locate["少林禅房"] = "少林蚕后安南房";
Name.Locate["少林天井"] = "少林天II安南井";
Name.Locate["北京永安门"] = "北京";
Name.Locate["北京濮阳"] = "濮阳";
Name.Locate["北京右安门城楼"] = "北京右欧UU安门城楼";
Name.Locate["兰州很府前广场"] = "兰州很";
Name.Locate["兰州很地藏殿"] = "兰州很地丈殿";
Name.Locate["兰州很斋堂"] = "兰州很斋很阿II堂";
Name.Locate["兰州很花厅"] = "兰州很花UU阿厅";
Name.Locate["兰州很大通铺"] = "兰州很大通欧南格铺";
Name.Locate["兰州很行宫大门"] = "兰州很星宫大门";
Name.Locate["兰州很兰州大车店"] = "兰州很马车行";
Name.Locate["兰州很大车店"] = "兰州很马车行";
Name.Locate["大轮寺礼佛大殿"] = "大轮寺";
Name.Locate["大轮寺大轮寺山门"] = "大轮寺山门";
Name.Locate["大轮寺赞普广场"] = "赞安南普UU";
Name.Locate["大轮寺藏民部落"] = "大轮寺丈民部落";
Name.Locate["大轮寺善禅渡"] = "大轮寺善蚕渡";
Name.Locate["大轮寺藏民村落"] = "大轮寺丈民村落";
Name.Locate["大轮寺马车店"] = "大轮寺马车行";
Name.Locate["大轮寺绝顶"] = "大轮寺绝UU饿顶";
Name.Locate["归云庄归云庄大门"] = "归云庄";
Name.Locate["归云庄树林"] = "归云庄树林II南";
Name.Locate["慕容湖边"] = "慕容";
Name.Locate["慕容绣房"] = "慕容绣IIUU房";
Name.Locate["慕容内室"] = "慕容内饿II室";
Name.Locate["慕容私塾"] = "慕容私塾很";
Name.Locate["慕容膳房"] = "慕容膳湖阿南房";
Name.Locate["神龙岛峰顶"] = "神龙岛";
Name.Locate["神龙岛山脚"] = "神龙岛山很安南脚";
Name.Locate["神龙岛山路"] = "神龙岛山路UU";
Name.Locate["神龙岛树林"] = "神龙岛树林II南";
Name.Locate["神龙岛黑龙堂"] = "神龙岛黑饿II龙堂";
Name.Locate["神龙岛香堂"] = "神龙岛香II阿南格堂";
Name.Locate["神龙岛潜龙堂"] = "神龙岛潜II阿南格龙堂";
Name.Locate["神龙岛山洞"] = "神龙岛山洞欧南格";
Name.Locate["神龙岛男弟子住所"] = "神龙岛男阿南弟子住所";
Name.Locate["灵鹫赤天部"] = "灵鹫赤II天部";
Name.Locate["灵鹫阳天部"] = "灵鹫阳阿南格天部";
Name.Locate["灵鹫松林"] = "灵鹫松林II南";
Name.Locate["全真崇玄台"] = "全真";
Name.Locate["全真奇草"] = "全真奇II草";
Name.Locate["全真升仙坊"] = "全真升仙坊很";
Name.Locate["全真校经房"] = "全真叫经房";
Name.Locate["梅庄很客厅"] = "梅庄很";
Name.Locate["梅庄很琴室"] = "梅庄很琴II南室";
Name.Locate["梅庄很梅庄天井"] = "梅庄很天井";

Name.ReplaceTable = {}
Name.ReplaceTable["计氏马车分行"] = "马车行";
Name.ReplaceTable["计氏马车总行"] = "马车行";
Name.ReplaceTable["关中车分行"] = "马车行";
Name.ReplaceTable["关中马车行"] = "马车行";
Name.ReplaceTable["边塞马车行"] = "马车行";
Name.ReplaceTable["兰州大车店"] = "马车行";
Name.ReplaceTable["青唐大车行"] = "马车行";
Name.ReplaceTable["中原马车行"] = "马车行";
Name.ReplaceTable["月记票号"] = "巴阿南克";
Name.ReplaceTable["月记银号"] = "巴阿南克";
Name.ReplaceTable["江南钱庄"] = "巴阿南克";
Name.ReplaceTable["泉州很泉州"] = "泉州很";
Name.ReplaceTable["城中心"] = "";
Name.ReplaceTable["中心广场"] = "";
Name.ReplaceTable["中央广场"] = "";
Name.ReplaceTable["长江北岸长江"] = "长江北";
Name.ReplaceTable["长江南岸长江"] = "长江南";
Name.ReplaceTable["黄河北岸黄河"] = "黄河北";
Name.ReplaceTable["黄河南岸黄河"] = "黄河南";
Name.ReplaceTable["峨嵋后山后山"] = "峨嵋后山";
Name.ReplaceTable["校场"] = "叫场";
Name.ReplaceTable["信阳"] = "信II南阳";
Name.ReplaceTable["一楼"] = "11";
Name.ReplaceTable["二楼"] = "22";
Name.ReplaceTable["一层"] = "11";
Name.ReplaceTable["二层"] = "22";
Name.ReplaceTable["三层"] = "33";
Name.ReplaceTable["四层"] = "44";
Name.ReplaceTable["五层"] = "55";
Name.ReplaceTable["六层"] = "66";
Name.ReplaceTable["七层"] = "77";
Name.ReplaceTable["一部"] = "11";
Name.ReplaceTable["二部"] = "22";
Name.ReplaceTable["三部"] = "33";
Name.ReplaceTable["四部"] = "44";
Name.ReplaceTable["五部"] = "55";
Name.ReplaceTable["六部"] = "66";
Name.ReplaceTable["七部"] = "77";
Name.ReplaceTable["八部"] = "88";
Name.ReplaceTable["九部"] = "99";
Name.ReplaceTable["禅房"] = "蚕房";
Name.ReplaceTable["乐府"] = "月府";
Name.ReplaceTable["宿处"] = "树处";
Name.ReplaceTable["浔阳楼"] = "浔阳楼欧UU";
Name.ReplaceTable["祚德庙"] = "当铺";
Name.ReplaceTable["灵鹫宫"] = "灵鹫";

if Common.id == "suineg" then
Way.tCantArrive = {"fzms", "fzmd", "fzmsfl",
		 "slssl", "slqyp", "slad", "slwxd",
		"hhnasp", "hhnasd", "hhnasl", "hhnadf",
		"pxwfms", "pxwfpxwmcbk",
		"btsghd", "btsgsl", "btsgpd", "btsgou", "btsgsd", "btsb",
		"gyzmhz", "dlsjxxl", "dlswtt"};
else
Way.tCantArrive = {"fzms", "fzmd", "fzmsfl",
		 "slssl", "slqyp", "slad", "slwxd",
		"hhnasp", "hhnasd", "hhnasl", "hhnadf",
		"pxwfms", "pxwfpxwmcbk",
		"btsghd", "btsgsl", "btsgpd", "btsgou", "btsgsd", "btsb",
		"gyzmhz", "dlsjxxl", "dlswtt"};
end
-------------------------------------
--              拦路               --
-------------------------------------
Way = Way or {};

Way.tBlockers = {};
Way.tBlockers["陆大有喝道：你不是华山弟子，不得入内。"] = {};
Way.tBlockers["陆大有喝道：你不是华山弟子，不得入内。"].name = "陆大有";
Way.tBlockers["陆大有喝道：你不是华山弟子，不得入内。"].id = "lu";
Way.tBlockers["陆大有喝道：你不是华山弟子，不得入内。"].place = "hsdt";
Way.tBlockers["童百熊说道：「你不是我日月神教弟子，来我教干什么？速速离开！」"] = {};
Way.tBlockers["童百熊说道：「你不是我日月神教弟子，来我教干什么？速速离开！」"].name = "童百熊";
Way.tBlockers["童百熊说道：「你不是我日月神教弟子，来我教干什么？速速离开！」"].id = "tong";
Way.tBlockers["童百熊说道：「你不是我日月神教弟子，来我教干什么？速速离开！」"].place = "ry";
Way.tBlockers["江百胜伸手拦住你说道：盟主很忙，现在不见外客，你下山去吧！"] = {};
Way.tBlockers["江百胜伸手拦住你说道：盟主很忙，现在不见外客，你下山去吧！"].name = "江百胜";
Way.tBlockers["江百胜伸手拦住你说道：盟主很忙，现在不见外客，你下山去吧！"].id = "jiang";
Way.tBlockers["江百胜伸手拦住你说道：盟主很忙，现在不见外客，你下山去吧！"].place = "ts";
Way.tBlockers["守山弟子说: 非我派弟子不许上峨嵋山。"] = {};
Way.tBlockers["守山弟子说: 非我派弟子不许上峨嵋山。"].name = "守山弟子";
Way.tBlockers["守山弟子说: 非我派弟子不许上峨嵋山。"].id = "dizi";
Way.tBlockers["守山弟子说: 非我派弟子不许上峨嵋山。"].place = "emsm";
Way.tBlockers["师太拦住了你的去路！！"] = {};
Way.tBlockers["师太拦住了你的去路！！"].name = "师太";
Way.tBlockers["师太拦住了你的去路！！"].id = "shi tai";
Way.tBlockers["师太拦住了你的去路！！"].place = "emsmd";
Way.tBlockers["黑甲军士挡住了你的去路。"] = {};
Way.tBlockers["黑甲军士挡住了你的去路。"].name = "黑甲军士";
Way.tBlockers["黑甲军士挡住了你的去路。"].id = "junshi";
Way.tBlockers["黑甲军士挡住了你的去路。"].place = "lzhxgdm";
Way.tBlockers["中年道长拦住你说道：后面是本派重地，你不是武当弟子，此去多有不便，请留步。"] = {};
Way.tBlockers["中年道长拦住你说道：后面是本派重地，你不是武当弟子，此去多有不便，请留步。"].name = "中年道长";
Way.tBlockers["中年道长拦住你说道：后面是本派重地，你不是武当弟子，此去多有不便，请留步。"].id = "daozhang";
Way.tBlockers["中年道长拦住你说道：后面是本派重地，你不是武当弟子，此去多有不便，请留步。"].place = "wdsqd";
Way.tBlockers["褚万里喝道：闲杂人等，不得入内。"] = {};
Way.tBlockers["褚万里喝道：闲杂人等，不得入内。"].name = "褚万里";
Way.tBlockers["褚万里喝道：闲杂人等，不得入内。"].id = "zhu";
Way.tBlockers["褚万里喝道：闲杂人等，不得入内。"].place = "dlwfdm";
Way.tBlockers["厚土旗众大声吼道：“你不是明教弟子，不许上山！”"] = {};
Way.tBlockers["厚土旗众大声吼道：“你不是明教弟子，不许上山！”"].name = "zhong";
Way.tBlockers["厚土旗众大声吼道：“你不是明教弟子，不许上山！”"].id = "";
Way.tBlockers["厚土旗众大声吼道：“你不是明教弟子，不许上山！”"].place = "";
Way.tBlockers["梅剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"] = {};
Way.tBlockers["梅剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].name = "梅剑";
Way.tBlockers["梅剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].id = "";
Way.tBlockers["梅剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].place = "ljdztdm";
Way.tBlockers["兰剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"] = {};
Way.tBlockers["兰剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].name = "梅剑";
Way.tBlockers["兰剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].id = "";
Way.tBlockers["兰剑伸手拦住你，说道：“非灵鹫宫弟子请回！”"].place = "ljdztdm";
Way.tBlockers["卫士对你大吼一声：站住，干什么的？(answer)"] = {};
Way.tBlockers["卫士对你大吼一声：站住，干什么的？(answer)"].name = "卫士";
Way.tBlockers["卫士对你大吼一声：站住，干什么的？(answer)"].id = "wei shi";
Way.tBlockers["卫士对你大吼一声：站住，干什么的？(answer)"].place = "lzhgdm";
Way.tBlockers["清兵说道：赶快滚开，这是你停留的地方吗？”"] = {};
Way.tBlockers["清兵说道：赶快滚开，这是你停留的地方吗？”"].name = "清兵";
Way.tBlockers["清兵说道：赶快滚开，这是你停留的地方吗？”"].id = "bing";
Way.tBlockers["清兵说道：赶快滚开，这是你停留的地方吗？”"].place = "tdf";
Way.tBlockers["红花会众说道：“阁下不是红花会弟子，最好不要进去。”"] = {};
Way.tBlockers["红花会众说道：“阁下不是红花会弟子，最好不要进去。”"].name = "红花会众";
Way.tBlockers["红花会众说道：“阁下不是红花会弟子，最好不要进去。”"].id = "";
Way.tBlockers["红花会众说道：“阁下不是红花会弟子，最好不要进去。”"].place = "xhhzfddm";
Way.tBlockers["王兴隆说道：“后面是我家，没事别瞎转悠。”"] = {};
Way.tBlockers["王兴隆说道：“后面是我家，没事别瞎转悠。”"].name = "王兴隆";
Way.tBlockers["王兴隆说道：“后面是我家，没事别瞎转悠。”"].id = "wang";
Way.tBlockers["王兴隆说道：“后面是我家，没事别瞎转悠。”"].place = "lafxlpzd";
Way.tBlockers["庄丁挡住了你：喂，你总该意思意思吧？"] = {};
Way.tBlockers["庄丁挡住了你：喂，你总该意思意思吧？"].name = "庄丁";
Way.tBlockers["庄丁挡住了你：喂，你总该意思意思吧？"].id = "";
Way.tBlockers["庄丁挡住了你：喂，你总该意思意思吧？"].place = "ll";
Way.tBlockers["锦衣卫上前挡住你说道：里面没什么好看的，马上离开这里....！"] = {};
Way.tBlockers["锦衣卫上前挡住你说道：里面没什么好看的，马上离开这里....！"].name = "锦衣卫";
Way.tBlockers["锦衣卫上前挡住你说道：里面没什么好看的，马上离开这里....！"].id = "jin";
Way.tBlockers["锦衣卫上前挡住你说道：里面没什么好看的，马上离开这里....！"].place = "";
Way.tBlockers["一等侍卫上前挡住你，朗声说道：皇宫禁地，禁止闲杂人等出入！"] = {};
Way.tBlockers["一等侍卫上前挡住你，朗声说道：皇宫禁地，禁止闲杂人等出入！"].name = "一等侍卫";
Way.tBlockers["一等侍卫上前挡住你，朗声说道：皇宫禁地，禁止闲杂人等出入！"].id = "gtn bjtzc";
Way.tBlockers["一等侍卫上前挡住你，朗声说道：皇宫禁地，禁止闲杂人等出入！"].place = "";
Way.tBlockers["门子挡住了你的去路。"] = {};
Way.tBlockers["门子挡住了你的去路。"].name = "门子";
Way.tBlockers["门子挡住了你的去路。"].id = "men zi";
Way.tBlockers["门子挡住了你的去路。"].place = "lzhmf";
Way.tBlockers["守卫喝道：闲杂人等，不得乱闯。"] = {};
Way.tBlockers["守卫喝道：闲杂人等，不得乱闯。"].name = "傅";
Way.tBlockers["守卫喝道：闲杂人等，不得乱闯。"].id = "fu";
Way.tBlockers["守卫喝道：闲杂人等，不得乱闯。"].place = "";
Way.tBlockers["官兵拦住了你:“闲杂人等不得上城楼。”"] = {};
Way.tBlockers["官兵拦住了你:“闲杂人等不得上城楼。”"].name = "官兵";
Way.tBlockers["官兵拦住了你:“闲杂人等不得上城楼。”"].id = "bing";
Way.tBlockers["官兵拦住了你:“闲杂人等不得上城楼。”"].place = "";
Way.tBlockers["桑结伸手拦住了你，一指门旁的牌子道：“没看到牌子么？施主还是请回吧。"] = {};
Way.tBlockers["桑结伸手拦住了你，一指门旁的牌子道：“没看到牌子么？施主还是请回吧。"].name = "桑结";
Way.tBlockers["桑结伸手拦住了你，一指门旁的牌子道：“没看到牌子么？施主还是请回吧。"].id = "";
Way.tBlockers["桑结伸手拦住了你，一指门旁的牌子道：“没看到牌子么？施主还是请回吧。"].place = "dlsxkt";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺男弟子休息的居所，你去不大方便吧？"] = {};
Way.tBlockers["护法喇嘛拦住你道：那里是本寺男弟子休息的居所，你去不大方便吧？"].name = "护法喇嘛";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺男弟子休息的居所，你去不大方便吧？"].id = "";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺男弟子休息的居所，你去不大方便吧？"].place = "dlsrmld";
Way.tBlockers["鼓手首领一言不发，闪身拦在你面前。"] = {};
Way.tBlockers["鼓手首领一言不发，闪身拦在你面前。"].name = "鼓手首领";
Way.tBlockers["鼓手首领一言不发，闪身拦在你面前。"].id = "gushou shouling";
Way.tBlockers["鼓手首领一言不发，闪身拦在你面前。"].place = "";
Way.tBlockers["神龙教弟子大声喝道：本教重地，外人不得入内！"] = {};
Way.tBlockers["神龙教弟子大声喝道：本教重地，外人不得入内！"].name = "神龙教弟子";
Way.tBlockers["神龙教弟子大声喝道：本教重地，外人不得入内！"].id = "dizi";
Way.tBlockers["神龙教弟子大声喝道：本教重地，外人不得入内！"].place = "";
Way.tBlockers["小道童拦住你说道：师祖正在静修，没什么事就不要去打扰。"] = {};
Way.tBlockers["小道童拦住你说道：师祖正在静修，没什么事就不要去打扰。"].name = "小道童";
Way.tBlockers["小道童拦住你说道：师祖正在静修，没什么事就不要去打扰。"].id = "daotong";
Way.tBlockers["小道童拦住你说道：师祖正在静修，没什么事就不要去打扰。"].place = "wdbcm";
Way.tBlockers["请下山去吧，免得自讨没趣。"] = {};
Way.tBlockers["请下山去吧，免得自讨没趣。"].name = "虚";
Way.tBlockers["请下山去吧，免得自讨没趣。"].id = "xu";
Way.tBlockers["请下山去吧，免得自讨没趣。"].place = "";
Way.tBlockers["山贼拦住了你的去路。"] = {};
Way.tBlockers["山贼拦住了你的去路。"].name = "山贼";
Way.tBlockers["山贼拦住了你的去路。"].id = "shan zei";
Way.tBlockers["山贼拦住了你的去路。"].place = "";
Way.tBlockers["梁发喝道：那里是家师寝室，不得入内。"] = {};
Way.tBlockers["梁发喝道：那里是家师寝室，不得入内。"].name = "梁发";
Way.tBlockers["梁发喝道：那里是家师寝室，不得入内。"].id = "liang fa";
Way.tBlockers["梁发喝道：那里是家师寝室，不得入内。"].place = "";
Way.tBlockers["官兵拦住了你的去路"] = {};
Way.tBlockers["官兵拦住了你的去路"].name = "";
Way.tBlockers["官兵拦住了你的去路"].id = "";
Way.tBlockers["官兵拦住了你的去路"].place = "";
Way.tBlockers["神龙教弟子大喝一声：里面是教主和夫人休息之低，外人不得入内。"] = {};
Way.tBlockers["神龙教弟子大喝一声：里面是教主和夫人休息之低，外人不得入内。"].name = "神龙教弟子";
Way.tBlockers["神龙教弟子大喝一声：里面是教主和夫人休息之低，外人不得入内。"].id = "";
Way.tBlockers["神龙教弟子大喝一声：里面是教主和夫人休息之低，外人不得入内。"].place = "";
Way.tBlockers["侍卫伸手拦住你朗声说道：里面没什么好看的，马上离开这里....！"] = {};
Way.tBlockers["侍卫伸手拦住你朗声说道：里面没什么好看的，马上离开这里....！"].name = "神龙教弟子";
Way.tBlockers["侍卫伸手拦住你朗声说道：里面没什么好看的，马上离开这里....！"].id = "shi wei";
Way.tBlockers["侍卫伸手拦住你朗声说道：里面没什么好看的，马上离开这里....！"].place = "";
Way.tBlockers["采花子挡住了你：我的小妞可不是给你们邪派弟子准备的！"] = {};
Way.tBlockers["采花子挡住了你：我的小妞可不是给你们邪派弟子准备的！"].name = "采花子";
Way.tBlockers["采花子挡住了你：我的小妞可不是给你们邪派弟子准备的！"].id = "caihua zi";
Way.tBlockers["采花子挡住了你：我的小妞可不是给你们邪派弟子准备的！"].place = "";
Way.tBlockers["严妈妈拦住了你：“你还是老实得呆在这里吧。”"] = {};
Way.tBlockers["严妈妈拦住了你：“你还是老实得呆在这里吧。”"].name = "严妈妈";
Way.tBlockers["严妈妈拦住了你：“你还是老实得呆在这里吧。”"].id = "yan";
Way.tBlockers["严妈妈拦住了你：“你还是老实得呆在这里吧。”"].place = "";
Way.tBlockers["管家挡住了你：我们家老爷不在家。"] = {};
Way.tBlockers["管家挡住了你：我们家老爷不在家。"].name = "管家";
Way.tBlockers["管家挡住了你：我们家老爷不在家。"].id = "guan";
Way.tBlockers["管家挡住了你：我们家老爷不在家。"].place = "";
Way.tBlockers["守军伸手拦住你说:此乃军机重地,岂能擅闯？"] = {};
Way.tBlockers["守军伸手拦住你说:此乃军机重地,岂能擅闯？"].name = "守军";
Way.tBlockers["守军伸手拦住你说:此乃军机重地,岂能擅闯？"].id = "shou jun";
Way.tBlockers["守军伸手拦住你说:此乃军机重地,岂能擅闯？"].place = "";
Way.tBlockers["崔员外挡住了你。"] = {};
Way.tBlockers["崔员外挡住了你。"].name = "崔员外";
Way.tBlockers["崔员外挡住了你。"].id = "cui";
Way.tBlockers["崔员外挡住了你。"].place = "";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"] = {};
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].name = "门卫";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].id = "meng wei";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].place = "";
Way.tBlockers["呼巴音手一伸，道：“这位施主，此处只有吐蕃王族才可以进去，请去别处随喜吧。"] = {};
Way.tBlockers["呼巴音手一伸，道：“这位施主，此处只有吐蕃王族才可以进去，请去别处随喜吧。"].name = "呼巴音";
Way.tBlockers["呼巴音手一伸，道：“这位施主，此处只有吐蕃王族才可以进去，请去别处随喜吧。"].id = "hu";
Way.tBlockers["呼巴音手一伸，道：“这位施主，此处只有吐蕃王族才可以进去，请去别处随喜吧。"].place = "";
Way.tBlockers["官兵们拦住了你的去路。"] = {};
Way.tBlockers["官兵们拦住了你的去路。"].name = "官兵";
Way.tBlockers["官兵们拦住了你的去路。"].id = "bing";
Way.tBlockers["官兵们拦住了你的去路。"].place = "";
Way.tBlockers["衙役喝道：「威……武……」"] = {};
Way.tBlockers["衙役喝道：「威……武……」"].name = "衙役";
Way.tBlockers["衙役喝道：「威……武……」"].id = "ya";
Way.tBlockers["衙役喝道：「威……武……」"].place = "";
Way.tBlockers["护法喇嘛拦住你道：“后山是本寺重地，你没有方丈的手谕，不能进去。"] = {};
Way.tBlockers["护法喇嘛拦住你道：“后山是本寺重地，你没有方丈的手谕，不能进去。"].name = "";
Way.tBlockers["护法喇嘛拦住你道：“后山是本寺重地，你没有方丈的手谕，不能进去。"].id = "";
Way.tBlockers["护法喇嘛拦住你道：“后山是本寺重地，你没有方丈的手谕，不能进去。"].place = "";
Way.tBlockers["简长老一把揪住你的衣领说：「慢着！」"] = {};
Way.tBlockers["简长老一把揪住你的衣领说：「慢着！」"].name = "简长老";
Way.tBlockers["简长老一把揪住你的衣领说：「慢着！」"].id = "jian";
Way.tBlockers["简长老一把揪住你的衣领说：「慢着！」"].place = "";
Way.tBlockers["杂役喇嘛拦住了你，小心翼翼地道：“施主留步，本寺方丈正在清修，不许打搅，施主"] = {};
Way.tBlockers["杂役喇嘛拦住了你，小心翼翼地道：“施主留步，本寺方丈正在清修，不许打搅，施主"].name = "杂役喇嘛";
Way.tBlockers["杂役喇嘛拦住了你，小心翼翼地道：“施主留步，本寺方丈正在清修，不许打搅，施主"].id = "lama";
Way.tBlockers["杂役喇嘛拦住了你，小心翼翼地道：“施主留步，本寺方丈正在清修，不许打搅，施主"].place = "";
Way.tBlockers["护法喇嘛拦住你道：“里面是本寺方丈及弟子居所，施主如欲礼佛还请去前面大殿。"] = {};
Way.tBlockers["护法喇嘛拦住你道：“里面是本寺方丈及弟子居所，施主如欲礼佛还请去前面大殿。"].name = "护法喇嘛";
Way.tBlockers["护法喇嘛拦住你道：“里面是本寺方丈及弟子居所，施主如欲礼佛还请去前面大殿。"].id = "lama";
Way.tBlockers["护法喇嘛拦住你道：“里面是本寺方丈及弟子居所，施主如欲礼佛还请去前面大殿。"].place = "";
Way.tBlockers["官兵拦住你骂道：“你以为你是谁啊？一个寻常百姓，难道还想进府见鳌大人？！"] = {};
Way.tBlockers["官兵拦住你骂道：“你以为你是谁啊？一个寻常百姓，难道还想进府见鳌大人？！"].name = "官兵";
Way.tBlockers["官兵拦住你骂道：“你以为你是谁啊？一个寻常百姓，难道还想进府见鳌大人？！"].id = "bing";
Way.tBlockers["官兵拦住你骂道：“你以为你是谁啊？一个寻常百姓，难道还想进府见鳌大人？！"].place = "";
Way.tBlockers["女管家挡住了你。"] = {};
Way.tBlockers["女管家挡住了你。"].name = "女管家";
Way.tBlockers["女管家挡住了你。"].id = "guan jia";
Way.tBlockers["女管家挡住了你。"].place = "";
Way.tBlockers["土匪把路一挡，狞笑道：怎么，想溜，没那么容易！"] = {};
Way.tBlockers["土匪把路一挡，狞笑道：怎么，想溜，没那么容易！"].name = "";
Way.tBlockers["土匪把路一挡，狞笑道：怎么，想溜，没那么容易！"].id = "";
Way.tBlockers["土匪把路一挡，狞笑道：怎么，想溜，没那么容易！"].place = "";
Way.tBlockers["总管大喝:那边是我家老爷的私人书房，请留步."] = {};
Way.tBlockers["总管大喝:那边是我家老爷的私人书房，请留步."].name = "";
Way.tBlockers["总管大喝:那边是我家老爷的私人书房，请留步."].id = "";
Way.tBlockers["总管大喝:那边是我家老爷的私人书房，请留步."].place = "";
Way.tBlockers["恕小寺不接待女客。女施主倘若一心向佛，何妨去峨眉山随喜？"] = {};
Way.tBlockers["恕小寺不接待女客。女施主倘若一心向佛，何妨去峨眉山随喜？"].name = "";
Way.tBlockers["恕小寺不接待女客。女施主倘若一心向佛，何妨去峨眉山随喜？"].id = "";
Way.tBlockers["恕小寺不接待女客。女施主倘若一心向佛，何妨去峨眉山随喜？"].place = "";
Way.tBlockers["亲兵拦住了你的去路,大声喝到:敢闯吕大人的家,你不想活了?"] = {};
Way.tBlockers["亲兵拦住了你的去路,大声喝到:敢闯吕大人的家,你不想活了?"].name = "";
Way.tBlockers["亲兵拦住了你的去路,大声喝到:敢闯吕大人的家,你不想活了?"].id = "";
Way.tBlockers["亲兵拦住了你的去路,大声喝到:敢闯吕大人的家,你不想活了?"].place = "";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺女弟子休息的居所，你去不大方便吧？"] = {};
Way.tBlockers["护法喇嘛拦住你道：那里是本寺女弟子休息的居所，你去不大方便吧？"].name = "";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺女弟子休息的居所，你去不大方便吧？"].id = "";
Way.tBlockers["护法喇嘛拦住你道：那里是本寺女弟子休息的居所，你去不大方便吧？"].place = "";
Way.tBlockers["护法喇嘛拦住你说道:最近寺内伙食紧张，外派弟子请到寺外自行解决。"] = {};
Way.tBlockers["护法喇嘛拦住你说道:最近寺内伙食紧张，外派弟子请到寺外自行解决。"].name = "";
Way.tBlockers["护法喇嘛拦住你说道:最近寺内伙食紧张，外派弟子请到寺外自行解决。"].id = "";
Way.tBlockers["护法喇嘛拦住你说道:最近寺内伙食紧张，外派弟子请到寺外自行解决。"].place = "";
Way.tBlockers["官兵们拦住了你的去路"] = {};
Way.tBlockers["官兵们拦住了你的去路"].name = "";
Way.tBlockers["官兵们拦住了你的去路"].id = "";
Way.tBlockers["官兵们拦住了你的去路"].place = "";
Way.tBlockers["保镖向你吼道：小杂种，这也是你来的地方?"] = {};
Way.tBlockers["保镖向你吼道：小杂种，这也是你来的地方?"].name = "";
Way.tBlockers["保镖向你吼道：小杂种，这也是你来的地方?"].id = "";
Way.tBlockers["保镖向你吼道：小杂种，这也是你来的地方?"].place = "";
Way.tBlockers["我大蒙古皇帝的金帐岂是由你说来就来说走就走的？"] = {};
Way.tBlockers["我大蒙古皇帝的金帐岂是由你说来就来说走就走的？"].name = "";
Way.tBlockers["我大蒙古皇帝的金帐岂是由你说来就来说走就走的？"].id = "meng";
Way.tBlockers["我大蒙古皇帝的金帐岂是由你说来就来说走就走的？"].place = "";
Way.tBlockers["门边的侍卫伸手把你给拦住了。"] = {};
Way.tBlockers["门边的侍卫伸手把你给拦住了。"].name = "";
Way.tBlockers["门边的侍卫伸手把你给拦住了。"].id = "";
Way.tBlockers["门边的侍卫伸手把你给拦住了。"].place = "";
Way.tBlockers["侍卫伸手拦住你说道：里面没什么好看的，马上离开这里....！"] = {};
Way.tBlockers["侍卫伸手拦住你说道：里面没什么好看的，马上离开这里....！"].name = "";
Way.tBlockers["侍卫伸手拦住你说道：里面没什么好看的，马上离开这里....！"].id = "";
Way.tBlockers["侍卫伸手拦住你说道：里面没什么好看的，马上离开这里....！"].place = "";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"] = {};
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].name = "";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].id = "";
Way.tBlockers["门卫把手一拦：你这种正派人物，老子一看就恶心，快滚！"].place = "";
Way.tBlockers["守山弟子说: 峨嵋非行凶之地，施主想要上山请解兵器。"] = {};
Way.tBlockers["守山弟子说: 峨嵋非行凶之地，施主想要上山请解兵器。"].name = "";
Way.tBlockers["守山弟子说: 峨嵋非行凶之地，施主想要上山请解兵器。"].id = "";
Way.tBlockers["守山弟子说: 峨嵋非行凶之地，施主想要上山请解兵器。"].place = "";



-------------------------------------
--              领悟               --
-------------------------------------
LingwuSkills = LingwuSkills or {};

if Common.id == "suineg" then
	LingwuSkills.arrLingwus = {"基本内功", "基本轻功", "基本剑法", "基本招架", "基本剑法", "基本掌法"}; --, "基本刀法"
	LingwuSkills.arrLians = {"玉女心法", "纤云步法", "玄铁剑法", "玄铁剑法", "玉女剑法", "黯然销魂掌"}; --, "胡家刀法"
	LingwuSkills.arrLiansCmd = {"", "", "unwield all;wield sword;jifa sword xuantie-jian", "", "jifa sword yunu-jianfa", "unwield all"}; --, "unwield all;wield blade;jifa blade hujia-daofa"
	LingwuSkills.strWayLingwu = "e;eat;drink;s";
	LingwuSkills.strWaySleep = "n;w;sleep";
elseif Common.id == "suinegy" then
	LingwuSkills.arrLingwus = {"基本内功", "基本轻功", "基本剑法", "基本招架", "基本剑法", "基本爪法"};
	LingwuSkills.arrLians = {"玉女心法", "纤云步法", "玄铁剑法", "玄铁剑法", "玉女剑法", "九阴白骨爪"};
	LingwuSkills.arrLiansCmd = {"", "", "wield sword;jifa sword xuantie-jian", "wield sword;jifa parry xuantie-jian", "wield sword;jifa sword yunu-jianfa", "unwield all;jifa claw jiuyin-baiguzhao;bei claw"};
	LingwuSkills.strWayLingwu = "e;eat;drink;s";
	LingwuSkills.strWaySleep = "n;w;sleep";
	--LingwuSkills.strWayLingwu = "n;e;e;n;n;n;e;enter";
	--LingwuSkills.strWaySleep = "out;w;s;s;s;w;w;s;sleep";
end

-------------------------------------
--              TASK               --
-------------------------------------
Task = Task or {};

Task.Object = {};
Task.Object["算筹"] = {};
Task.Object["算筹"].id = "suan chou";
Task.Object["算筹"].place = "tyhzxw";
Task.Object["算筹"].npc = "yinggu";
Task.Object["断龙刀"] = {};
Task.Object["断龙刀"].id = "duanlong dao";
Task.Object["断龙刀"].place = "yzczhy";
Task.Object["断龙刀"].npc = "tian";
Task.Object["虎符"] = {};
Task.Object["虎符"].id = "hu fu";
Task.Object["虎符"].place = "pxwfsf";
Task.Object["虎符"].npc = "wu";
Task.Object["带血的丝巾"] = {};
Task.Object["带血的丝巾"].id = "si jin";
Task.Object["带血的丝巾"].place = "ssbxzl";
Task.Object["带血的丝巾"].npc = "lang";
Task.Object["玉女剑"] = {};
Task.Object["玉女剑"].id = "yunv jian";
Task.Object["玉女剑"].place = "xiaolongnv";
Task.Object["玉女剑"].npc = "xiao";
Task.Object["白扇"] = {};
Task.Object["白扇"].id = "bai shan";
Task.Object["白扇"].place = "ouyangke";
Task.Object["白扇"].npc = "ke";
Task.Object["玉石子"] = {};
Task.Object["玉石子"].id = "yu shizi";
Task.Object["玉石子"].place = "thd";
Task.Object["玉石子"].npc = "huang";
Task.Object["竹剑"] = {};
Task.Object["竹剑"].id = "zhu jian";
Task.Object["竹剑"].place = "xiaolongnv";
Task.Object["竹剑"].npc = "yang";
Task.Object["先天罡气谱"] = {};
Task.Object["先天罡气谱"].id = "gangqi pu";
Task.Object["先天罡气谱"].place = "wangchongyang";
Task.Object["先天罡气谱"].npc = "wang";
Task.Object["鱼杆"] = {};
Task.Object["鱼杆"].id = "yu gan";
Task.Object["鱼杆"].place = "typb";
Task.Object["鱼杆"].npc = "yuyin";
Task.Object["骰子"] = {};
Task.Object["骰子"].id = "sai zi";
Task.Object["骰子"].place = "weixiaobao";
Task.Object["骰子"].npc = "wei";
Task.Object["易筋经"] = {};
Task.Object["易筋经"].id = "yijin jing";
Task.Object["易筋经"].place = "jiumozhi";
Task.Object["易筋经"].npc = "zhi";
Task.Object["头巾"] = {};
Task.Object["头巾"].id = "tou jin";
Task.Object["头巾"].place = "thdsf";
Task.Object["头巾"].npc = "fu";
Task.Object["太极剑"] = {};
Task.Object["太极剑"].id = "taiji jian";
Task.Object["太极剑"].place = "zhangsanfeng";
Task.Object["太极剑"].npc = "zhang";
Task.Object["花名册"] = {};
Task.Object["花名册"].id = "huaming ce";
Task.Object["花名册"].place = "tdh";
Task.Object["花名册"].npc = "chen";
Task.Object["天蚕衣"] = {};
Task.Object["天蚕衣"].id = "tiancan yi";
Task.Object["天蚕衣"].place = "liqiushui";
Task.Object["天蚕衣"].npc = "li";
Task.Object["念珠"] = {};
Task.Object["念珠"].id = "nian zhu";
Task.Object["念珠"].place = "miejue";
Task.Object["念珠"].npc = "shitai";
Task.Object["布袋"] = {};
Task.Object["布袋"].id = "bu dai";
Task.Object["布袋"].place = "hongqigong";
Task.Object["布袋"].npc = "hong";
Task.Object["烧饼"] = {};
Task.Object["烧饼"].id = "shao bing";
Task.Object["烧饼"].place = "thdjct";
Task.Object["烧饼"].npc = "gu";
Task.Object["佩剑"] = {};
Task.Object["佩剑"].id = "pei jian";
Task.Object["佩剑"].place = "hssgy";
Task.Object["佩剑"].npc = "linghu";
Task.Object["香罗帕"] = {};
Task.Object["香罗帕"].id = "luo pa";
Task.Object["香罗帕"].place = "wlslhfd";
Task.Object["香罗帕"].npc = "duan";
Task.Object["玉佩"] = {};
Task.Object["玉佩"].id = "yu pei";
Task.Object["玉佩"].place = "hskt";
Task.Object["玉佩"].npc = "yue";
Task.Object["毒经"] = {};
Task.Object["毒经"].id = "du jing";
Task.Object["毒经"].place = "jxnh";
Task.Object["毒经"].npc = "li";
Task.Object["木剑"] = {};
Task.Object["木剑"].id = "mu jian";
Task.Object["木剑"].place = "zhangwuji";
Task.Object["木剑"].npc = "zhang";
Task.Object["淑女剑"] = {};
Task.Object["淑女剑"].id = "shunv jian";
Task.Object["淑女剑"].place = "hs";
Task.Object["淑女剑"].npc = "ning";
Task.Object["神木鼎"] = {};
Task.Object["神木鼎"].id = "shenmu ding";
Task.Object["神木鼎"].place = "dingchunqiu";
Task.Object["神木鼎"].npc = "ding";
Task.Object["紫霞袍"] = {};
Task.Object["紫霞袍"].id = "zixia pao";
Task.Object["紫霞袍"].place = "hs";
Task.Object["紫霞袍"].npc = "yue";
Task.Object["水缸"] = {};
Task.Object["水缸"].id = "shui gang";
Task.Object["水缸"].place = "tyyz";
Task.Object["水缸"].npc = "qiu";
Task.Object["破碗"] = {};
Task.Object["破碗"].id = "po wan";
Task.Object["破碗"].place = "xscmz";
Task.Object["破碗"].npc = "man";
Task.Object["九阴真经"] = {};
Task.Object["九阴真经"].id = "jiuyin zhenjing";
Task.Object["九阴真经"].place = "guojing";
Task.Object["九阴真经"].npc = "guo";
Task.Object["掌门指环"] = {};
Task.Object["掌门指环"].id = "zhi huan";
Task.Object["掌门指环"].place = "ljdzt";
Task.Object["掌门指环"].npc = "xu";
Task.Object["官印"] = {};
Task.Object["官印"].id = "guan yin";
Task.Object["官印"].place = "bjtt";
Task.Object["官印"].npc = "duo";
Task.Object["包袱"] = {};
Task.Object["包袱"].id = "bao fu";
Task.Object["包袱"].place = "ryzqtlw";
Task.Object["包袱"].npc = "xiang";
Task.Object["盟主令"] = {};
Task.Object["盟主令"].id = "mengzhu ling";
Task.Object["盟主令"].place = "ssbzhsf";
Task.Object["盟主令"].npc = "chu";




Common.tQuest = {"hsz", "gsz", "tz", "mzj", "hyd", "songxin", "murong", "dazuo", "wat", "pl", "qiuqianzhang", "pozhen", "job", "job 2", "zja", "护镖任务", "护镖任务lin", "护镖任务zuo", "task", "ssb", "xf", "job_pozhen"};


Location = Location or {};

Location.strAreaNames = {"峨眉后山","中原","西湖梅庄","曲阜","信阳","泰山","长江南岸","长江北岸","长江","黄河南岸","黄河北岸","嘉兴","泉州","江州","牙山","临安府","西湖","福州","南昌","镇江","苏州","归云庄","小山村","张家口","麒麟村","大理城中","昆明","平西王府","桃源","岳阳","成都","建康府南城","建康府北城","北京","康亲王府","天坛","紫禁城","洛阳","灵州","晋阳","日月神教","神龙岛","襄阳","丝绸之路","长安","扬州","杀手帮","丐帮","岳王墓","姑苏慕容","桃花岛","峨嵋","天龙寺","武当山","华山","全真","古墓","少林寺","白驼山","星宿","明教","灵鹫","凌霄城","大轮寺","兰州","无量山","杭州提督府","天地会","湟中","荆州"}
Location.strAreaNamesS= {"峨眉后山","中原","梅庄很","曲阜","信阳","泰山","长江南岸","长江北岸","长江南岸","黄河南岸","黄河北岸","嘉兴","泉州很","江州","牙山","临安府","西湖","福州","南昌","镇江","苏州","归云庄","小山村","张家口","麒麟村","大理","昆明","平西王府","桃源","岳阳","成都","建康","建康","北京","康亲王府","天坛","紫禁城","洛阳","灵州","晋阳","日月","神龙岛","襄阳","丝绸之路","长安","扬州","杀手帮","丐帮","岳王墓","慕容","桃花岛","峨嵋","天龙寺","武当","华山","全真","古墓","少林","白驼","星宿","明教","灵鹫","凌霄","大轮寺","兰州很","无量山","提督府","天地会","湟中","荆州"}

Location.strAreaIDs = {}
Location.strAreaIDs["中原"] = "zy"
Location.strAreaIDs["西湖梅庄"] = "meizhuang"
Location.strAreaIDs["曲阜"] = "qufu"
Location.strAreaIDs["信阳"] = "xinyang"
Location.strAreaIDs["泰山"] = "taishang"
Location.strAreaIDs["长江南岸"] = "cjndk2"
Location.strAreaIDs["长江北岸"] = "cjbab21"
Location.strAreaIDs["长江"] = "cjndk5"
Location.strAreaIDs["黄河南岸"] = "mjd"
Location.strAreaIDs["黄河北岸"] = "hhbda"
Location.strAreaIDs["嘉兴"] = "jiaxing"
Location.strAreaIDs["泉州"] = "quanzhou"
Location.strAreaIDs["江州"] = "jiangzhou"
Location.strAreaIDs["牙山"] = "yashan"
Location.strAreaIDs["临安府"] = "hz"
Location.strAreaIDs["西湖"] = "hhh"
Location.strAreaIDs["福州"] = "fuzhou"
Location.strAreaIDs["南昌"] = "nc"
Location.strAreaIDs["镇江"] = "zhenjiang"
Location.strAreaIDs["苏州"] = "suzhou"
Location.strAreaIDs["归云庄"] = "guiyunzhuang"
Location.strAreaIDs["小山村"] = "xiaocun"
Location.strAreaIDs["张家口"] = "zjk"
Location.strAreaIDs["麒麟村"] = "qlc"
Location.strAreaIDs["大理城中"] = "dali"
Location.strAreaIDs["昆明"] = "kunming"
Location.strAreaIDs["平西王府"] = "pingxiwang"
Location.strAreaIDs["桃源"] = "taoyuan"
Location.strAreaIDs["岳阳"] = "yueyang"
Location.strAreaIDs["成都"] = "chengdu"
Location.strAreaIDs["建康府南城"] = "jkcym"
Location.strAreaIDs["建康府北城"] = "jkqlm"
Location.strAreaIDs["北京"] = "bj"
Location.strAreaIDs["康亲王府"] = "kqwf"
Location.strAreaIDs["天坛"] = "bjzymwdj3"
Location.strAreaIDs["紫禁城"] = "bjzymwdj3"
Location.strAreaIDs["洛阳"] = "luoyang"
Location.strAreaIDs["灵州"] = "linzhou"
Location.strAreaIDs["晋阳"] = "jinyang"
Location.strAreaIDs["日月神教"] = "riyue"
Location.strAreaIDs["神龙岛"] = "shenlongdao"
Location.strAreaIDs["襄阳"] = "xiangyang"
Location.strAreaIDs["荆州"] = "xiangyang"
Location.strAreaIDs["丝绸之路"] = "sc"
Location.strAreaIDs["长安"] = "ca"
Location.strAreaIDs["扬州"] = "yz"
Location.strAreaIDs["杀手帮"] = "ssbgc"
Location.strAreaIDs["丐帮"] = "gbad1"
Location.strAreaIDs["岳王墓"] = "ywm"
Location.strAreaIDs["姑苏慕容"] = "mt"
Location.strAreaIDs["桃花岛"] = "taohua"
Location.strAreaIDs["峨嵋"] = "emei"
Location.strAreaIDs["天龙寺"] = "tianlongsi"
Location.strAreaIDs["武当山"] = "wudang"
Location.strAreaIDs["华山"] = "huashan"
Location.strAreaIDs["全真"] = "quanzhen"
Location.strAreaIDs["古墓"] = "gumu"
Location.strAreaIDs["少林寺"] = "shaolin"
Location.strAreaIDs["白驼山"] = "baituo"
Location.strAreaIDs["星宿"] = "xingxiu"
Location.strAreaIDs["明教"] = "mingjiao"
Location.strAreaIDs["灵鹫"] = "lingjiu"
Location.strAreaIDs["凌霄城"] = "lxcm"
Location.strAreaIDs["大轮寺"] = "zp"
Location.strAreaIDs["兰州"] = "lanzhou"
Location.strAreaIDs["无量山"] = "tlswlshs"
Location.strAreaIDs["峨眉后山"] = "emei"
Location.strAreaIDs["杭州提督府"] = "tdf"
Location.strAreaIDs["天地会"] = "bj"

Location.tBLID = {};
Location.tBLID["中原"]="xuchang";
Location.tBLID["曲阜"]="qufu";
Location.tBLID["信阳"]="xinyang";
Location.tBLID["泰山"]="taishan";
Location.tBLID["长江南岸"]="cjnab";
Location.tBLID["长江北岸"]="cjbab21";
Location.tBLID["长江"]="cjnab";
Location.tBLID["黄河南岸"]="hhna20";
Location.tBLID["黄河北岸"]="hhba21";
Location.tBLID["嘉兴"]="jiaxing";
Location.tBLID["泉州"]="quanzhou";
Location.tBLID["江州"]="jiangzhou";
Location.tBLID["牙山"]="yashan";
Location.tBLID["临安府"]="hangzhou";
Location.tBLID["西湖"]="xhdjq";
Location.tBLID["福州"]="fuzhou";
Location.tBLID["南昌"]="nanchang";
Location.tBLID["镇江"]="zhenjiang";
Location.tBLID["苏州"]="suzhou";
Location.tBLID["归云庄"]="guiyunzhuang";
Location.tBLID["小山村"]="xiaocun";
Location.tBLID["张家口"]="zhangjiakou";
Location.tBLID["麒麟村"]="qilincun";
Location.tBLID["大理城中"]="dali";
Location.tBLID["大理"]="dali";
Location.tBLID["昆明"]="kunming";
Location.tBLID["平西王府"]="pingxiwang";
Location.tBLID["桃源"]="taoyuan";
Location.tBLID["岳阳"]="yueyang";
Location.tBLID["成都"]="chengdu";
Location.tBLID["建康府南城"]="jk";
Location.tBLID["建康府北城"]="jk";
Location.tBLID["北京"]="beijing";
Location.tBLID["康亲王府"]="beijing";
Location.tBLID["天坛"]="beijing";
Location.tBLID["紫禁城"]="beijing";
Location.tBLID["洛阳"]="luoyang";
Location.tBLID["灵州"]="lingzhou";
Location.tBLID["晋阳"]="jinyang";
Location.tBLID["日月神教"]="riyue";
Location.tBLID["日月"]="riyue";
Location.tBLID["神龙岛"]="sldmt";
Location.tBLID["襄阳"]="xiangyang";
Location.tBLID["荆州"]="xiangyang";
Location.tBLID["丝绸之路"]="sichou";
Location.tBLID["长安"]="changan";
Location.tBLID["扬州"]="yangzhou";
Location.tBLID["杀手帮"]="yangzhou";
Location.tBLID["丐帮"]="yangzhou";
Location.tBLID["岳王墓"]="yuewangmu";
Location.tBLID["姑苏慕容"]="mrmt";
Location.tBLID["慕容"]="mrmt";
Location.tBLID["桃花岛"]="thdhtan";
Location.tBLID["峨嵋"]="embgsdm";
Location.tBLID["天龙寺"]="tianlongsi";
Location.tBLID["武当山"]="wdsm";
Location.tBLID["武当"]="wdsm";
Location.tBLID["华山"]="hsjx";
Location.tBLID["全真"]="quanzhen";
Location.tBLID["古墓"]="gumu";
Location.tBLID["少林寺"]="2xu";
Location.tBLID["少林"]="2xu";
Location.tBLID["白驼山"]="baituo";
Location.tBLID["白驼"]="baituo";
Location.tBLID["星宿"]="xingxiu";
Location.tBLID["明教"]="mingjiao";
Location.tBLID["灵鹫"]="lingjiu";
Location.tBLID["凌霄城"]="lxqt2";
Location.tBLID["凌霄"]="lxqt2";
Location.tBLID["大轮寺"]="zanpu";
Location.tBLID["兰州"]="lanzhoudalu";
Location.tBLID["兰州很"]="lanzhoudalu";
Location.tBLID["无量山"]="tianlongsi";
Location.tBLID["峨眉后山"]="emei";
Location.tBLID["杭州提督府"]="tidufu";
Location.tBLID["提督府"]="tidufu";
Location.tBLID["天地会"]="lygcdns";
Location.tBLID["湟中"]="hzzx";
Location.tBLID["西湖梅庄"]="mzh";
Location.tBLID["梅庄很"]="mzh";

Way.strBlPlaceName = {};
Way.strBlPlaceName["中原"] = "许昌城";
Way.strBlPlaceName["曲阜"] = "孔庙";
Way.strBlPlaceName["信阳"] = "小广场";
Way.strBlPlaceName["泰山"] = "南天门";
Way.strBlPlaceName["长江"] = "长江岸边";
Way.strBlPlaceName["长江南岸"] = "长江岸边";
Way.strBlPlaceName["长江北岸"] = "长江岸边";
Way.strBlPlaceName["黄河南岸"] = "黄河南岸";
Way.strBlPlaceName["黄河北岸"] = "黄河北岸";
Way.strBlPlaceName["嘉兴"] = "嘉兴城";
Way.strBlPlaceName["泉州"] = "城中心";
Way.strBlPlaceName["江州"] = "中央广场";
Way.strBlPlaceName["牙山"] = "牙山湾中心";
Way.strBlPlaceName["临安府"] = "大理寺";
Way.strBlPlaceName["西湖"] = "段家桥";
Way.strBlPlaceName["福州"] = "城中心";
Way.strBlPlaceName["南昌"] = "城中心";
Way.strBlPlaceName["镇江"] = "广场";
Way.strBlPlaceName["苏州"] = "宝带桥";
Way.strBlPlaceName["归云庄"] = "归云庄大门";
Way.strBlPlaceName["小山村"] = "打谷场";
Way.strBlPlaceName["张家口"] = "广场";
Way.strBlPlaceName["麒麟村"] = "小广场";
Way.strBlPlaceName["大理城中"] = "中心广场";
Way.strBlPlaceName["昆明"] = "中心广场";
Way.strBlPlaceName["平西王府"] = "平西王府大门";
Way.strBlPlaceName["桃源"] = "桃源县境";
Way.strBlPlaceName["岳阳"] = "城中心";
Way.strBlPlaceName["成都"] = "总督府门前";
Way.strBlPlaceName["建康府南城"] = "中城";
Way.strBlPlaceName["建康府北城"] = "中城";
Way.strBlPlaceName["北京"] = "永安门";
Way.strBlPlaceName["康亲王府"] = "永安门";
Way.strBlPlaceName["天坛"] = "永安门";
Way.strBlPlaceName["紫禁城"] = "永安门";
Way.strBlPlaceName["洛阳"] = "洛阳中心广场";
Way.strBlPlaceName["灵州"] = "城中心";
Way.strBlPlaceName["晋阳"] = "朝曦门内街";
Way.strBlPlaceName["日月神教"] = "小村庄";
Way.strBlPlaceName["神龙岛"] = "码头";
Way.strBlPlaceName["襄阳"] = "城中心";
Way.strBlPlaceName["荆州"] = "城中心";
Way.strBlPlaceName["丝绸之路"] = "丝绸之路";
Way.strBlPlaceName["长安"] = "朱雀大街";
Way.strBlPlaceName["扬州"] = "中央广场";
Way.strBlPlaceName["杀手帮"] = "中央广场";
Way.strBlPlaceName["丐帮"] = "中央广场";
Way.strBlPlaceName["岳王墓"] = "墓前小道";
Way.strBlPlaceName["姑苏慕容"] = "码头";
Way.strBlPlaceName["慕容"] = "码头";
Way.strBlPlaceName["桃花岛"] = "海滩";
Way.strBlPlaceName["峨嵋"] = "报国寺大门";
Way.strBlPlaceName["天龙寺"] = "三元宫";
Way.strBlPlaceName["武当山"] = "武当山门";
Way.strBlPlaceName["华山"] = "华山脚下";
Way.strBlPlaceName["全真"] = "崇玄台";
Way.strBlPlaceName["古墓"] = "断龙石";
Way.strBlPlaceName["少林寺"] = "少林寺";
Way.strBlPlaceName["白驼山"] = "大门";
Way.strBlPlaceName["星宿"] = "巨岩";
Way.strBlPlaceName["明教"] = "山门";
Way.strBlPlaceName["灵鹫"] = "百丈涧";
Way.strBlPlaceName["凌霄城"] = "桥头";
Way.strBlPlaceName["凌霄"] = "桥头";
Way.strBlPlaceName["大轮寺"] = "赞普广场";
Way.strBlPlaceName["兰州"] = "大路";
Way.strBlPlaceName["无量山"] = "三元宫";
Way.strBlPlaceName["峨眉后山"] = "千佛庵大殿";
Way.strBlPlaceName["杭州提督府"] = "提督府正门";
Way.strBlPlaceName["提督府"] = "提督府正门";
Way.strBlPlaceName["天地会"] = "棺材店内室";
Way.strBlPlaceName["湟中"] = "湟中中心";
Way.strBlPlaceName["西湖梅庄"] = "客厅";
Way.strBlPlaceName["梅庄很"] = "客厅";

Way.strBlPlaceID = {};
Way.strBlPlaceID["zy"] = "中原";
Way.strBlPlaceID["qf"] = "曲阜";
Way.strBlPlaceID["xiny"] = "信阳";
Way.strBlPlaceID["ts"] = "泰山";
Way.strBlPlaceID["cjna"] = "长江";
Way.strBlPlaceID["cjba"] = "长江北岸";
Way.strBlPlaceID["hhna"] = "黄河南岸";
Way.strBlPlaceID["hhba"] = "黄河北岸";
Way.strBlPlaceID["jx"] = "嘉兴";
Way.strBlPlaceID["qzh"] = "泉州";
Way.strBlPlaceID["jz"] = "江州";
Way.strBlPlaceID["ys"] = "牙山";
Way.strBlPlaceID["laf"] = "临安府";
Way.strBlPlaceID["xh"] = "西湖";
Way.strBlPlaceID["fz"] = "福州";
Way.strBlPlaceID["nc"] = "南昌";
Way.strBlPlaceID["zj"] = "镇江";
Way.strBlPlaceID["sz"] = "苏州";
Way.strBlPlaceID["gyz"] = "归云庄";
Way.strBlPlaceID["xc"] = "小山村";
Way.strBlPlaceID["zjk"] = "张家口";
Way.strBlPlaceID["qlc"] = "麒麟村";
Way.strBlPlaceID["dl"] = "大理城中";
Way.strBlPlaceID["km"] = "昆明";
Way.strBlPlaceID["pxwf"] = "平西王府";
Way.strBlPlaceID["ty"] = "桃源";
Way.strBlPlaceID["yy"] = "岳阳";
Way.strBlPlaceID["cd"] = "成都";
Way.strBlPlaceID["jkn"] = "建康府南城";
Way.strBlPlaceID["jkb"] = "建康府北城";
Way.strBlPlaceID["bj"] = "北京";
Way.strBlPlaceID["kqwf"] = "康亲王府";
Way.strBlPlaceID["tt"] = "天坛";
Way.strBlPlaceID["zjc"] = "紫禁城";
Way.strBlPlaceID["ly"] = "洛阳";
Way.strBlPlaceID["lz"] = "灵州";
Way.strBlPlaceID["jy"] = "晋阳";
Way.strBlPlaceID["ry"] = "日月神教";
Way.strBlPlaceID["sld"] = "神龙岛";
Way.strBlPlaceID["xy"] = "襄阳";
Way.strBlPlaceID["sczl"] = "丝绸之路";
Way.strBlPlaceID["ca"] = "长安";
Way.strBlPlaceID["yz"] = "扬州";
Way.strBlPlaceID["ssb"] = "杀手帮";
Way.strBlPlaceID["gb"] = "丐帮";
Way.strBlPlaceID["ywm"] = "岳王墓";
Way.strBlPlaceID["mr"] = "姑苏慕容";
Way.strBlPlaceID["thd"] = "桃花岛";
Way.strBlPlaceID["em"] = "峨嵋";
Way.strBlPlaceID["tls"] = "天龙寺";
Way.strBlPlaceID["wd"] = "武当山";
Way.strBlPlaceID["hs"] = "华山";
Way.strBlPlaceID["qz"] = "全真";
Way.strBlPlaceID["gm"] = "古墓";
Way.strBlPlaceID["sl"] = "少林寺";
Way.strBlPlaceID["bt"] = "白驼山";
Way.strBlPlaceID["xx"] = "星宿";
Way.strBlPlaceID["mj"] = "明教";
Way.strBlPlaceID["lj"] = "灵鹫";
Way.strBlPlaceID["lx"] = "凌霄城";
Way.strBlPlaceID["dls"] = "大轮寺";
Way.strBlPlaceID["lzh"] = "兰州";
Way.strBlPlaceID["wls"] = "无量山";
Way.strBlPlaceID["emhs"] = "峨眉后山";
Way.strBlPlaceID["tdf"] = "杭州提督府";
Way.strBlPlaceID["tdh"] = "天地会";
Way.strBlPlaceID["hz"] = "湟中";
Way.strBlPlaceID["mzh"] = "西湖梅庄";

Common.tZiHua = {};
Common.tZiHua["黄庭经"] = "huangting jing";
Common.tZiHua["金明池夺标图"] = "duobiao tu";
Common.tZiHua["虎噬鹿器座"] = "luqi zuo";
Common.tZiHua["江帆楼阁图"] = "louge tu";
Common.tZiHua["颜家庙碑"] = "yanjia miaobei";
Common.tZiHua["莲鹤方壶"] = "lianhe fanghu";
Common.tZiHua["蜀素帖"] = "shusu tie";
Common.tZiHua["化度寺碑"] = "huadusi bei";
Common.tZiHua["禾大人面纹方鼎"] = "fang ding";
Common.tZiHua["夜明珠"] = "yeming zhu";
Common.tZiHua["合卺杯"] = "hejin bei";
Common.tZiHua["神策军碑"] = "shence junbei";
Common.tZiHua["枯木竹石图"] = "kumu tu";
Common.tZiHua["富春山居图"] = "shanju tu";
Common.tZiHua["秋山晚翠图"] = "wancui tu";
Common.tZiHua["赤壁图"] = "chibi tu";
Common.tZiHua["衡方碑"] = "hengfang bei";
Common.tZiHua["蓝釉灯"] = "lanyou deng";
Common.tZiHua["三尺珊瑚"] = "shanhu";
Common.tZiHua["龙门二十品"] = "ershi pin";
Common.tZiHua["睿鹤图"] = "ruihe tu";
Common.tZiHua["龙耳虎足方壶"] = "fang hu";
Common.tZiHua["历代帝王图"] = "diwang tu";
Common.tZiHua["寿春堂记"] = "shouchuntang ji";
